### ISSUE TITLE
Error Al ejecutar downloads.download_datasets()

### ISSUE THREAD

**Issue by iarroyof** [VilmaGlez/historical_sources#4]
>>> downloads.download_datasets()
Traceback (most recent call last):
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/historical_sources/downloads.py", line 13, in download_datasets
    os.mkdir(nuevaruta)
FileExistsError: [Errno 17] File exists: '/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/historical_sources/results_final'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/historical_sources/downloads.py", line 15, in download_datasets
    print("Created " % nuevaruta)
TypeError: not all arguments converted during string formatting

**Comment by VilmaGlez** [comment]
Resuelto
