### ISSUE TITLE
Error al ejecutar  from historical_sources import set_train_modules

### ISSUE THREAD

**Issue by iarroyof** [VilmaGlez/historical_sources#5]
>>> from historical_sources import set_train_modules
/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
2023-02-12 15:07:53.219839: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-12 15:07:53.220630: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/confidence_checks/task_checklists/__init__.py:15: UserWarning: To use the checklist integration you should install ``allennlp`` with the "checklist" extra (e.g. ``pip install allennlp[checklist]``) or just install checklist after the fact.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/historical_sources/set_train_modules.py", line 3, in <module>
    from historical_sources.classification import extract_sentences
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/historical_sources/classification.py", line 6, in <module>
    allenslr=pretrained.load_predictor('structured-prediction-srl-bert')
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp_models/pretrained.py", line 61, in load_predictor
    pretrained_models = pretrained_models or get_pretrained_models()
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp_models/pretrained.py", line 35, in get_pretrained_models
    import_plugins()
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/common/plugins.py", line 79, in import_plugins
    import_module_and_submodules(
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/common/util.py", line 362, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/common/util.py", line 362, in import_module_and_submodules
    import_module_and_submodules(subpackage, exclude=exclude)
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/common/util.py", line 351, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/commands/checklist.py", line 22, in <module>
    from allennlp.confidence_checks.task_checklists.task_suite import TaskSuite
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/confidence_checks/task_checklists/__init__.py", line 4, in <module>
    from allennlp.confidence_checks.task_checklists.task_suite import TaskSuite
  File "/home/iarroyof/anaconda3/envs/transferl/lib/python3.9/site-packages/allennlp/confidence_checks/task_checklists/task_suite.py", line 6, in <module>
    from checklist.test_suite import TestSuite
ModuleNotFoundError: No module named 'checklist'

**Comment by VilmaGlez** [comment]
pip install checklist
pip install cached-path==1.1.2
